### ISSUE TITLE
파일전송 종료 흐름제어 동작 정리

### ISSUE THREAD

**Issue by happyhj** [happyhj/neardrop#38]
받는 측은 갯수를 세다가 자신이 다 받았으면 파일 잘받았다는 메시지 JSON 보내고 종료로 가기  (현행과 같음)
보내는 측은 갯수만 세다가 마지막꺼 send 호출하고 바로 종료하지말고 파일다 잘 받았다는 응답 받은 후에 종료 프로세스로 가기 (현행은 이렇지 않음)

**Comment by FourwingsY** [comment]
이 이슈는 해결되었지만, 흐름제어가 들어가면서 sender와 saver 로직이 많이 갈라지는 느낌이네요.
이걸 어떻게 분리할 수 없을까 고민이 들기 시작합니다.

**Comment by happyhj** [comment]
센더나 세이버에 로우한 작업에 대한 기능만 남겨놓고 컨트롤러를 따로 뽑아내는 것도 좋아 보여요.
